models/Omset.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "omset".
 *
 * @property int $id_omset
 * @property string $tanggal
 * @property string $no_op
 * @property string $no_kw
 * @property string $customer
 * @property string $pembelian
 * @property string $saldo_awal
 * @property string $dp_cash
 * @property string $dp_bank
 * @property string $pelunasan
 * @property string $pelunasan_bank
 * @property string $bg_mundur
 * @property string $potongan
 * @property string $saldo_akhir
 * @property string $marketing
 */
class Omset extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'omset';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['tanggal', 'no_op', 'saldo_awal','jenis_pengerjaan','marketing','customer'], 'required'],
            [['id_omset'], 'integer'],
            [['jenis_pengerjaan','tanggal', 'no_op', 'no_kw','customer', 'pembelian', 'saldo_awal', 'dp_cash', 'dp_bank', 'pelunasan', 'pelunasan_bank', 'bg_mundur', 'potongan', 'saldo_akhir'], 'string', 'max' => 50],
            [['id_omset'], 'unique'],
            [['no_op'], 'autonumber', 'format'=>'SA.'.date('Y-m-d').'.?'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_omset' => 'Id Omset',
            'jenis_pengerjaan' => 'Jenis Pengerjaan',
            'tanggal' => 'Tanggal',
            'no_op' => 'No. Op',
            'no_kw' => 'No. Kw',
            'customer' => 'Customer',
            'pembelian' => 'Pembelian',
            'saldo_awal' => 'Saldo Awal',
            'dp_cash' => 'Dp Cash',
            'dp_bank' => 'Dp Bank',
            'pelunasan' => 'Pelunasan',
            'pelunasan_bank' => 'Pelunasan Bank',
            'bg_mundur' => 'Bg Mundur',
            'potongan' => 'Potongan',
            'saldo_akhir' => 'Saldo Akhir',
            'marketing' => 'Marketing'
        ];
    }
}

controllers/OmsetController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Omset;
use app\models\OmsetSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use kartik\mpdf\Pdf;

/**
 * OmsetController implements the CRUD actions for Omset model.
 */
class OmsetController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            [
                'class' => 'mdm\autonumber\Behavior',
                'attribute' => 'no_op', // required
                'value' => 'SA.'.date('Y-m-d').'.?' , // format auto number. '?' will be replaced with generated number
                'digit' => 4 // optional, default to null. 
            ],
        ];
    }

    /**
     * Lists all Omset models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new OmsetSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Omset model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
    public function actionReport() {
        // get your HTML raw content without any layouts or scripts
        $content = $this->renderPartial('report');
        
        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_UTF8, 
            // A4 paper format
            'format' => Pdf::FORMAT_A4, 
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT, 
            // stream to browser inline
            'destination' => Pdf::DEST_DOWNLOAD, 
            // your html content input
            'content' => $content,  
            // format content from your own css file if needed or use the

            // any css to be embedded if required
            'cssInline' => '.kv-heading-1{font-size:18px}', 
             // set mPDF properties on the fly
            'options' => ['title' => 'Krajee Report Title'],
             // call mPDF methods on the fly
            'methods' => [ 
                'SetTitle' => 'Privacy Policy - Krajee.com',
            'SetSubject' => 'Generating PDF files via yii2-mpdf extension has never been easy',
            'SetHeader' => ['Laporan Omset||Dicetak Pada: ' . date("r")],
            'SetFooter' => ['|Page {PAGENO}|'],
            'SetAuthor' => 'Kartik Visweswaran',
            'SetCreator' => 'Kartik Visweswaran',
            'SetKeywords' => 'Krajee, Yii2, Export, PDF, MPDF, Output, Privacy, Policy, yii2-mpdf',
            ]
        ]);
        
        // return the pdf output as per the destination setting
        return $pdf->render(); 
    }

    /**
     * Creates a new Omset model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Omset();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_omset]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Omset model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id_omset]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Omset model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Omset model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Omset the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Omset::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/omset/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Omset */
/* @var $form yii\widgets\ActiveForm */
?>
<?php
//CSS Ini digunakan untuk menampilkan required field (field wajib isi)
?>
<style>
    div.required label.control-label:after {
        content: ' *';
        color: red;
    }
</style>

<?php
//CSS Ini digunakan untuk overide jarak antar form biar tidak terlalu jauh
?>
<style>
    .form-group {
        margin-bottom: 0px;
    }
</style>

<div class="omset-form box box-success">

<div class="box-header with-border">
        <p>
            <?= Html::a('<< Kembali', ['index'], ['class' => 'btn btn-warning']) ?>
        </p>
    </div>
    <div class="box-header with-border">
        <?php $form = ActiveForm::begin([
            'layout' => 'horizontal',
            //'action' => ['index1'],
            //'method' => 'get',
            'fieldConfig' => [
                'horizontalCssClasses' => [
                    'label' => 'col-sm-2',
                    'offset' => 'col-sm-offset-2',
                    'wrapper' => 'col-sm-8',
                ],
            ],
        ]); ?>

    <!-- <?php $form->field($model, 'id_omset')->textInput() ?> -->
    <?php $dataPengerjaan = ['INTERIOR (PENDING)' => 'INTERIOR (PENDING)',
                             'INTERIOR UMUM' => 'INTERIOR UMUM',
                             'PERPINTUAN PROYEK (PENDING)' => 'PERPINTUAN PROYEK (PENDING)',
                             'PERPINTUAN UMUM' => 'PERPINTUAN UMUM',
                             'PERATAPAN + TERALIS UMUM'=>'PERATAPAN + TERALIS UMUM'];
        echo $form->field($model, 'jenis_pengerjaan')->dropDownList($dataPengerjaan,
            ['prompt' => '-Pilih Jenis Pengerjaan-']); ?>
      
    <?= $form->field($model, 'tanggal',['inputOptions' => [
'autocomplete' => 'off']])->widget(
        \dosamigos\datepicker\DatePicker::className(), [
        // inline too, not bad
        'inline' => false,
        'id' => 'assetitemincident-incident_date',
        'template' => '{addon}{input}',
        'clientOptions' => [
            'autoclose' => true,
            'format' => 'dd/mm/yy',
            'defaultDate' => date('dd/mm/Y'),

        ]
    ]) ?>

    <?= $form->field($model, 'no_op',['inputOptions' => [
'autocomplete' => 'off']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'no_kw',['inputOptions' => [
'autocomplete' => 'off']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'customer',['inputOptions' => [
'autocomplete' => 'off']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'pembelian',['inputOptions' => [
'autocomplete' => 'off']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'saldo_awal',['inputOptions' => [
'autocomplete' => 'off']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'dp_cash',['inputOptions' => [
'autocomplete' => 'off']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'dp_bank',['inputOptions' => [
'autocomplete' => 'off']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'pelunasan',['inputOptions' => [
'autocomplete' => 'off']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'pelunasan_bank',['inputOptions' => [
'autocomplete' => 'off']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'bg_mundur',['inputOptions' => [
'autocomplete' => 'off']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'potongan',['inputOptions' => [
'autocomplete' => 'off']])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'saldo_akhir')->textInput(['maxlength' => true,'readonly'=> true]) ?>

    <?= $form->field($model, 'marketing',
     ['inputOptions' => ['value' => Yii::$app->user->identity->username]])
     ->textInput(['maxlength' => true,'readonly'=> true]) ?>

   
    <div class="box-footer">
            <div class='form-group'>
                <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

</div>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $("#omset-dp_bank, #omset-saldo_awal, #omset-dp_cash, #omset-pelunasan, #omset-pelunasan_bank, #omset-potongan").keyup(function() {
            var saldo  = $("#omset-saldo_awal").val();
            var dpbank = $("#omset-dp_bank").val();
            var dpcash = $("#omset-dp_cash").val();
            var pelunasan = $("#omset-pelunasan").val();
            var pelunasanbank = $("#omset-pelunasan_bank").val();
            var potongan = $("#omset-potongan").val();
            var total = saldo - dpcash - dpbank - pelunasan - pelunasanbank - potongan;
            $("#omset-saldo_akhir").val(total);
        });
    });
</script>

views/omset/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\OmsetSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="omset-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id_omset') ?>

    <?= $form->field($model, 'jenis_pengerjaan') ?>

    <?= $form->field($model, 'tanggal') ?>

    <?= $form->field($model, 'no_op') ?>

    <?= $form->field($model, 'no_kw') ?>

    <?php // echo $form->field($model, 'customer') ?>

    <?php // echo $form->field($model, 'pembelian') ?>

    <?php // echo $form->field($model, 'saldo_awal') ?>

    <?php // echo $form->field($model, 'dp_cash') ?>

    <?php // echo $form->field($model, 'dp_bank') ?>

    <?php // echo $form->field($model, 'pelunasan') ?>

    <?php // echo $form->field($model, 'pelunasan_bank') ?>

    <?php // echo $form->field($model, 'bg_mundur') ?>

    <?php // echo $form->field($model, 'potongan') ?>

    <?php // echo $form->field($model, 'saldo_akhir') ?>

    <?php // echo $form->field($model, 'marketing') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/omset/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Omset */

$this->title = 'Tambah Omset';
$this->params['breadcrumbs'][] = ['label' => 'Omsets', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="omset-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/omset/index.php
<?php

use yii\helpers\Html;
// use yii\grid\GridView;
use kartik\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel app\models\OmsetSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Omset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="omset-index box box-success">
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <div class="box-header with-border">
        <p>
            <?= Html::a('Tambah Omset', ['create'], ['class' => 'btn btn-success']) ?>
            <?= Html::a('<i class="glyphicon glyphicon-print"></i> Cetak Laporan', ['/omset/report'], [
                        'class'=>'btn btn-danger', 
                        'target'=>'_blank', 
                        'data-toggle'=>'tooltip', 
                        'title'=>'Will open the generated PDF file in a new window'
            ]); ?>
        </p>

        <?= GridView::widget([
        'dataProvider' => $dataProvider,
        // 'filterModel' => $searchModel,
        'showPageSummary' => true,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            
            [
                'attribute' => 'jenis_pengerjaan',
                'headerOptions' => ['style' => 'width:150px'],
            ],
            [
                'attribute' => 'tanggal',
                'headerOptions' => ['style' => 'width:150px'],
            ],
            // 'id_omset',
            'no_op',
            'no_kw',
            [
                'attribute' => 'customer',
                'headerOptions' => ['style' => 'width:150px'],
            ],
            [
                'attribute'=> 'pembelian',
                'format' => ['decimal'],
                'pageSummary' => true
            ],
            [
                'attribute'=> 'saldo_awal',
                'format' => ['decimal'],
                'pageSummary' => true
            ],
            [
                'attribute'=> 'dp_cash',
                'format' => ['decimal'],
                'pageSummary' => true
            ],
            [
                'attribute'=> 'dp_bank',
                'format' => ['decimal'],
                'pageSummary' => true
            ],
            [
                'attribute'=> 'pelunasan',
                'format' => ['decimal'],
                'pageSummary' => true
            ],
            [
                'attribute'=> 'pelunasan_bank',
                'format' => ['decimal'],
                'pageSummary' => true
            ],
            'bg_mundur',
            'potongan',
            [
                'attribute'=> 'saldo_akhir',
                'format' => ['decimal'],
                'pageSummary' => true
            ],
            'marketing',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
    </div>

    
</div>

views/omset/report.php
<?php 
echo 'informasi';
?>

views/omset/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Omset */

$this->title = 'Update Omset: ' . $model->id_omset;
$this->params['breadcrumbs'][] = ['label' => 'Omsets', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id_omset, 'url' => ['view', 'id' => $model->id_omset]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="omset-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/omset/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Omset */

$this->title = $model->no_op;
$this->params['breadcrumbs'][] = ['label' => 'Omsets', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="omset-view box box-success">

<div class="box-header with-border">
        <p>
            <?= Html::a('<< Back', ['index'], ['class' => 'btn btn-warning']) ?>
            <?= Html::a('Update', ['update', 'id' => $model->id_omset], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Delete', ['delete', 'id' => $model->id_omset], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method' => 'post',
                ],
            ]) ?>
        </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'jenis_pengerjaan',
            // 'id_omset',
            'tanggal',
            'no_op',
            'no_kw',
            'customer',
            'pembelian',
            'saldo_awal',
            'dp_cash',
            'dp_bank',
            'pelunasan',
            'pelunasan_bank',
            'bg_mundur',
            'potongan',
            'saldo_akhir',
            'marketing'
        ],
    ]) ?>
</div>